name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install required packages
      run: |
        brew install shellcheck
        pip install --upgrade pip

    # Lint check
    - name: Check init_macos.sh
      run: shellcheck ${GITHUB_WORKSPACE}/init_macos.sh

        #     - name: Check init_archlinux.sh
        #       run: shellcheck ${GITHUB_WORKSPACE}/init_archlinux.sh

    # - name: Check .zshrc
    #   run: shellcheck ${GITHUB_WORKSPACE}/config/zsh/.zshrc --exclude=SC2148,SC1090


