name: macos

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  dotfiles:
    name: "dotfiles"
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

      - name: Run brew bundle
        run: |
          brew bundle
          brew link --overwrite cocoapods
          brew unlink go@1.20
          brew link --overwrite go
